jobs:
  include:
    # CI Build for /feature branches
    - stage: "CI Feature Build"
      name: build
      if: branch =~ /^feature\/.*$/
      language: csharp
      mono: none
      dotnet: 2.2.103
      before_install:
        - cd src/DNI.API
      install:
        - dotnet restore
      script:
        - dotnet build DNI.API.csproj -c Release
      name: test
      if: branch =~ /^feature\/.*$/
      script:
        - dotnet test --filter TestType!=Integration
    -
      name: "Angular Build"
      language: node_js
      node_js: 12.16.1
      before_install:
        - cd src/DNI.Web
      install:
        - npm set progress=false
        - npm install --no-progress
      script:
        - npm run lint
        - npm run build:ssr
        # TODO: Headless angular tests
    # CD Build for PRs and master
    - stage: "CD Docker Build & Deploy"
      name: build
      if: branch = master
      services:
        - docker
      script:
        - docker-compose build
        - echo $DEPLOY_SERVER
        # TODO: Deploy docker image
