language: csharp
mono: none
dotnet: 2.2.103

# services:
#   - docker

jobs:
  include:
    - name: "CI Build"
      # on:
      #   all_branches: true
      #condition: $TRAVIS_BRANCH =~ /^feature\/.*$/
      stage: test
      # script: "dotnet restore"
      script: "dotnet test --filter TestType!=Integration"
