language: csharp
mono: none
dotnet: 2.2.103

# services:
#   - docker

jobs:
  include:
    - branches:
        only:
          - /^feature\/.*$/
      install:
        - dotnet restore
      script:
        - dotnet test --filter TestType!=Integration
        - pwd
    - branches:
        only:
          - test
      # install:
      #   - dotnet restore
      script:
        - pwd
