jobs:
  include:
    # CI Build for /feature branches
    - name: ".Net Build"
      if: branch =~ /^feature\/.*$/
      language: csharp
      mono: none
      dotnet: 2.2.103
      install:
        - dotnet restore
      script:
        - dotnet test --filter TestType!=Integration
    - name: "Angular Build"
      if: branch =~ /^feature\/.*$/
      language: node_js
      node_js: 10.13
      before_install:
        - cd src/DNI.Web
      install:
        - npm set progress=false
        - npm install --no-progress
      script:
        - npm run lint
        - npm run build:ssr
        # TODO: Headless angular tests
    # CD Build for PRs and master
    - name: "Docker Build"
      if: branch = master
      services:
        - docker
      script:
        - docker-compose build
        # TODO: Deploy docker image
