# language: csharp
# mono: none
# dotnet: 2.2.103

# services:
#   - docker

jobs:
  include:
    - if: branch =~ /^feature\/.*$/
      # install:
      #   - dotnet restore
      script:
        #- dotnet test --filter TestType!=Integration
        - echo 'feature'
        - pwd
    - if: branch = test
      # install:
      #   - dotnet restore
      script:
        - echo 'test'
        - pwd
