# Do not build for branches unless they are listed here
branches:
  only:
    - master
    - /^feature\/.*$/
deploy:
  provider: script
  script: bash deploy.sh
  on:
    tags: true

# Define stages and jobs for each branch
jobs:
  include:
    # CI Build for /feature branches
    - stage: "CI Feature Build"
      name: ".Net Build & Test"
      language: csharp
      mono: none
      dotnet: 3.1.2
      if: branch =~ /^feature\/.*$/
      install:
        - dotnet restore
      script:
        - dotnet build --no-restore --nologo -c $ASPNET_CONFIGURATION
        - for dir in test/*.Tests/; do (cd "$dir" && dotnet test -c $ASPNET_CONFIGURATION --no-restore --no-build --nologo --filter TestType!=Integration); done
    - name: "Angular Build, Lint & Test"
      language: node_js
      node_js: 12.16.1
      if: branch =~ /^feature\/.*$/
      before_install:
        - cd src/DNI.Web
      install:
        - npm set progress=false
        - npm install --no-progress
      script:
        - npm run lint
        - npm run build:ssr
        # TODO: Headless angular tests
    # CD Build for PRs and master
    - stage: "CD Docker Build & Deploy"
      name: build
      language: minimal
      if: branch = master
      services:
        - docker
      script:
        #- docker-compose build
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo PR; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo DEPLOY; fi'
