language: csharp
mono: none
dotnet: 2.2.103

# services:
#   - docker

jobs:
  include:
    - stage: test
    name: "CI Build"
      # script: "dotnet restore"
      script: "dotnet test --filter TestType!=Integration"
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ /^feature\/.*$/
