jobs:
  include:
    - name: ".Net Build"
      if: branch =~ /^feature\/.*$/
      language: csharp
      mono: none
      dotnet: 2.2.103
      install:
        - dotnet restore
      script:
        - dotnet test --filter TestType!=Integration
    - name: "Angular Build"
      if: branch =~ /^feature\/.*$/
      language: node_js
      node_js: 10.13
      install:
        - npm set progress=false
        - npm install --no-progress
      script:
        - npm run lint
        - npm run test
        - npm run build:ssr
    - name: "Docker Build"
      if: branch = master
      services:
        - docker
      script:
        - docker-compose build
        # TODO: Deploy
