language: csharp
mono: none
dotnet: 2.2.103

# services:
#   - docker

branches:
  only:
    - master
    - feature/*

install:
  - dotnet restore"
script:
  - "dotnet test --filter TestType!=Integration"
  - "pwd"
