

services:
  - docker

jobs:
  include:
    - name: "CI Build"
    if: branch =~ /^feature\/.*$/
    language: csharp
    mono: none
    dotnet: 2.2.103
    - stage: test
      # script: "dotnet restore"
      script: "dotnet test --filter TestType!=Integration"

