

services:
  - docker

jobs:
  include:
    - name: "CI Build"
    language: csharp
    mono: none
    dotnet: 2.2.103
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ /^feature\/.*$/
      stage: test
      # script: "dotnet restore"
      script: "dotnet test --filter TestType!=Integration"
