version: '3.8'

services:
  # Dotnet Core API
  dni.api.restore:
    image: ${IMAGE_PREFIX}dniapi:latest-restore
    container_name: dniapi.restore.${ANGULAR_ENV}
    build: &api-restore-build
      context: .
      dockerfile: src/DNI.API/Dockerfile
      target: restore
      cache_from:
        - ${IMAGE_PREFIX}dniapi:latest-restore
    restart: "no"
  dni.api.build:
    image: ${IMAGE_PREFIX}dniapi:latest-build
    depends_on:
      - dni.api.restore
    container_name: dniapi.build.${ANGULAR_ENV}
    build: &api-build-build
      <<: *api-restore-build
      target: build
      args:
        - PROJECT_DIR=src/DNI.API/
        - PROJECT_NAME=DNI.API
        - ASPNET_CONFIGURATION=${ASPNET_CONFIGURATION}
      cache_from:
        - ${IMAGE_PREFIX}dniapi:latest-restore
        - ${IMAGE_PREFIX}dniapi:latest-build
    restart: "no"
  dni.api:
    image: ${IMAGE_PREFIX}dniapi:latest
    depends_on:
      - dni.api.restore
      - dni.api.build
    container_name: dniapi.${ANGULAR_ENV}
    ports:
      - "${LOCAL_API_PORT}:80"
    build:
      <<: *api-build-build
      target: final
      cache_from:
        - ${IMAGE_PREFIX}dniapi:latest-restore
        - ${IMAGE_PREFIX}dniapi:latest-build
        - ${IMAGE_PREFIX}dniapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CAPTCHA__SecretKey=${CAPTCHA_KEY}
      - General__SmtpServer=${SMTP_SERVER}
      - General__SmtpServerPort=${SMTP_PORT}
      - General__SmtpUsername=${SMTP_USERNAME}
      - General__SmtpPassword=${SMTP_PASSWORD}
      - General__SmtpEnableSSL=${SMTP_ENABLE_SSL}
      - General__ErrorEmailFrom=${ERROR_EMAIL_FROM}
      - General__ErrorEmailTo=${ERROR_EMAIL_TO}
      - General__ContactEmailTo=${CONTACT_EMAIL_TO}
    volumes:
      - ${LOG_MOUNT_PATH}:/app/logs/
    restart: unless-stopped

  # Angular Website
  dni.web.restore:
    image: ${IMAGE_PREFIX}dniweb:latest-restore
    container_name: dniweb.restore.${ANGULAR_ENV}
    depends_on:
      - dni.api
    build: &web-restore-build
      context: src/DNI.Web/
      target: restore
      cache_from:
        - ${IMAGE_PREFIX}dniweb:latest-restore
    restart: "no"
  dni.web.build:
    image: ${IMAGE_PREFIX}dniweb:latest-build
    container_name: dniweb.build.${ANGULAR_ENV}
    depends_on:
      - dni.web.restore
    build: &web-build-build
      <<: *web-restore-build
      target: build
      args:
        - ANGULAR_ENV=${ANGULAR_ENV}
      cache_from:
        - ${IMAGE_PREFIX}dniweb:latest-restore
        - ${IMAGE_PREFIX}dniweb:latest-build
    restart: "no"
  dni.web:
    image: ${IMAGE_PREFIX}dniweb:latest
    container_name: dniweb.${ANGULAR_ENV}
    depends_on:
      - dni.web.restore
      - dni.web.build
    ports:
     - "${LOCAL_WEB_PORT}:4200"
    build:
      <<: *web-build-build
      target: final
      cache_from:
        - ${IMAGE_PREFIX}dniweb:latest-restore
        - ${IMAGE_PREFIX}dniweb:latest-build
        - ${IMAGE_PREFIX}dniweb:latest
    restart: unless-stopped
