version: '3.6'

services:
  # Dotnet Core API
  dni.api:
    image: dniapi/${BUILD_ENVIRONMENT}:latest
    container_name: dniapi.${BUILD_ENVIRONMENT}
    depends_on:
      - dni.smtp
    ports:
      - "${LOCAL_API_PORT}:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CAPTCHA__SecretKey=${CAPTCHA_KEY}
      - SendGrid__ApiKey=${SENDGRID_KEY}
      - YouTube__ApiKey=${YOUTUBE_API_KEY}
      - General__SmtpServer=dni.smtp
      - General__ErrorEmailFrom=${ERROR_EMAIL_FROM}
      - General__ErrorEmailTo=${ERROR_EMAIL_TO}
      - General__ContactEmailTo=${CONTACT_EMAIL_TO}
    build:
      context: . # Nnnngh
      dockerfile: src/DNI.API/Dockerfile
      args:
        - PROJECT_DIR=src/DNI.API/
        - PROJECT_NAME=DNI.API
        - ASPNET_CONFIGURATION=${ASPNET_CONFIGURATION}
      # cache_from:
        # - dniapi/${BUILD_ENVIRONMENT}:latest
    volumes:
      - ${LOG_MOUNT_PATH}:/app/logs/
    restart: unless-stopped

  # Angular Website
  dni.web:
    image: dniweb/${BUILD_ENVIRONMENT}:latest
    container_name: dniweb.${BUILD_ENVIRONMENT}
    depends_on:
      - dni.api
    ports:
     - "${LOCAL_WEB_PORT}:80"
    build:
      context: src/DNI.Web/
      args:
        - ANGULAR_ENV=${BUILD_ENVIRONMENT}
      # cache_from:
        # - dniweb/${BUILD_ENVIRONMENT}:latest
    restart: unless-stopped

  # SMTP Server
  dni.smtp:
    image: dnismtp/${BUILD_ENVIRONMENT}:latest
    container_name: dnismtp.${BUILD_ENVIRONMENT}
    environment:
      - MAILNAME=${SMTP_MAILNAME}
      - PORT=25
      - DISABLE_IPV6=TRUE
      - SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}
      - SMARTHOST_PORT=${SMARTHOST_PORT}
      - SMARTHOST_USER=${SMARTHOST_USER}
      - SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}
      - SMARTHOST_ALIASES=${SMARTHOST_ALIASES}
    build:
      context: src/DNI.SMTP/
      # cache_from:
        # - dnismtp/${BUILD_ENVIRONMENT}:latest
    restart: unless-stopped
