version: '3.6'

services:
  # Dotnet Core API
  dni.api:
    image: ${IMAGE_PREFIX}dniapi/${BUILD_ENVIRONMENT}:latest
    container_name: dniapi.${BUILD_ENVIRONMENT}
    ports:
      - "${LOCAL_API_PORT}:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CAPTCHA__SecretKey=${CAPTCHA_KEY}
      - General__SmtpServer=${SMTP_SERVER}
      - General__SmtpServerPort=${SMTP_PORT}
      - General__SmtpEnableSSL=${SMTP_ENABLE_SSL}
      - General__SmtpUsername=${SMTP_USERNAME}
      - General__SmtpPassword=${SMTP_PASSWORD}
      - General__ErrorEmailFrom=${ERROR_EMAIL_FROM}
      - General__ErrorEmailTo=${ERROR_EMAIL_TO}
      - General__ContactEmailTo=${CONTACT_EMAIL_TO}
    build:
      context: . # Nnnngh
      dockerfile: src/DNI.API/Dockerfile
      args:
        - PROJECT_DIR=src/DNI.API/
        - PROJECT_NAME=DNI.API
        - ASPNET_CONFIGURATION=${ASPNET_CONFIGURATION}
      cache_from:
        - ${IMAGE_PREFIX}dniapi/${BUILD_ENVIRONMENT}:latest
    volumes:
      - ${LOG_MOUNT_PATH}:/app/logs/
    restart: unless-stopped

  # Angular Website
  dni.web:
    image: ${IMAGE_PREFIX}dniweb/${BUILD_ENVIRONMENT}:latest
    container_name: dniweb.${BUILD_ENVIRONMENT}
    depends_on:
      - dni.api
    ports:
     - "${LOCAL_WEB_PORT}:80"
    build:
      context: src/DNI.Web/
      args:
        - ANGULAR_ENV=${BUILD_ENVIRONMENT}
      cache_from:
        - ${IMAGE_PREFIX}dniweb/${BUILD_ENVIRONMENT}:latest
    restart: unless-stopped
