name: DNI Stream Website CD Build

on:
  push:
    # TODO: Remove the "branches" node for go live
    branches:
      - release/*
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  BUILD_ENVIRONMENT: prod # Required for docker-compose too
  IMAGE_TAG: 2.0.2 # Remove for go live - dealt with in the "Get image tags" task
  DOCKER_REGISTRY: docker.pkg.github.com

jobs:
  dockerimages:
    env:
      IMAGE_PREFIX: docker.pkg.github.com/dnistream/dni.website/ # Used in the docker-compose.yml file
      API_IMAGE: docker.pkg.github.com/dnistream/dni.website/dniapi # Cannot use variable references here - hence repeat info
      WEB_IMAGE: docker.pkg.github.com/dnistream/dni.website/dniweb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to docker packages
        run: docker login ${DOCKER_REGISTRY} --username dnistream --password ${{ secrets.GITHUB_TOKEN }}
      # - name: Get image tags
      #   run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF/refs\/tags\//}
      - name: Pull latest images for cache
        run: |
          docker pull ${API_IMAGE}:latest 2>&1;
          docker pull ${WEB_IMAGE}:latest 2>&1;
          docker image ls;
      - name: Build docker images
        env:
          ASPNETCORE_ENVIRONMENT: Production
          CAPTCHA_KEY: ${{ secrets.CAPTCHA_KEY }}
          ASPNET_CONFIGURATION: Release
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_ENABLE_SSL: ${{ secrets.SMTP_ENABLE_SSL }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          LOG_MOUNT_PATH: ${{ secrets.LOG_MOUNT_PATH }}
          LOCAL_WEB_PORT: 8080
          LOCAL_API_PORT: 8181
          ERROR_EMAIL_FROM: ${{ secrets.ERROR_EMAIL_FROM }}
          ERROR_EMAIL_TO: ${{ secrets.ERROR_EMAIL_TO }}
          CONTACT_EMAIL_TO: ${{ secrets.CONTACT_EMAIL_TO }}
        run: |
          docker-compose build --parallel --compress;
          docker image ls;
      - name: Tag images
        run: |
          docker tag ${API_IMAGE}:latest ${API_IMAGE}:${IMAGE_TAG};
          docker tag ${WEB_IMAGE}:latest ${WEB_IMAGE}:${IMAGE_TAG};
          docker image ls;
      - name: Push images
        run: |
          docker push ${API_IMAGE}:latest;
          docker push ${WEB_IMAGE}:latest;
          docker push ${API_IMAGE}:${IMAGE_TAG};
          docker push ${WEB_IMAGE}:${IMAGE_TAG};
      - name: Docker logout
        run: docker logout ${DOCKER_REGISTRY}
      # TODO: Pull and run on web server agent (install github actions agent on server)
