name: DNI Stream Website CD Build

on:
  push:
    branches:
      - master
    # tags:
    #   - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  dockerimages:
    runs-on: ubuntu-latest
    steps:
    - name: Build docker images
      run: docker-compose build --parallel
    - name: Log in to docker packages
      run: docker login docker.pkg.github.com --username dnistream --password ${{ secrets.GITHUB_TOKEN }}
