name: DNI Stream Website CD Build

on:
  push:
    branches:
      - master
    # tags:
    #   - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  dockerimages:
    runs-on: ubuntu-latest
    steps:
    - name: Test release
      run: docker info
